"""
Document intelligence run config: local prescription PDFs vs (future) Unity Catalog tables.

For now the pipeline runs entirely off local PDF + JSON files generated by
`data/prescription_pdf_generator/generate_prescription_pdfs_local.py`.
When the dbt medallion project for document intelligence is wired up, we can
extend this config with a catalog schema similar to the other use cases.
"""

import os
from pathlib import Path

from use_cases.env_utils import is_running_on_databricks

_DEFAULT_LOCAL_BASE_DIR = Path(__file__).resolve().parents[2] / "prescription_pdfs"


def get_local_base_dir() -> Path:
    """
    Base directory containing `documents/`, `labels/`, `annotated/`.
    Override with DOCINT_BASE_DIR or LOCAL_DATA_PATH.
    """
    p = os.environ.get("DOCINT_BASE_DIR") or os.environ.get(
        "LOCAL_DATA_PATH", str(_DEFAULT_LOCAL_BASE_DIR)
    )
    return Path(p).resolve()


def get_config() -> dict:
    """
    Single config dict for the document intelligence pipeline.
    - base_dir: Path to prescription_pdfs root
    - documents_dir: Path to PDFs
    - labels_dir: Path to JSON labels (ground truth or annotations)
    - annotated_dir: Path to human-corrected labels
    - on_databricks: bool (is_running_on_databricks())
    """
    base_dir = get_local_base_dir()
    return {
        "base_dir": base_dir,
        "documents_dir": base_dir / "documents",
        "labels_dir": base_dir / "labels",
        "annotated_dir": base_dir / "annotated",
        "on_databricks": is_running_on_databricks(),
    }
